#!/bin/bash
HAVE_GCC=45 USE_COMPILERCRTSTUFF=no MKPIC=no MKATF=no MKGCC=no MKGCCCMDS=no MKBINUTILS=no MKGDB=no MKCRYPTO=no MKCOMPLEX=no MKDOC=no MKDYNAMICROOT=no MKHTML=no MKINET6=no MKINFO=no MKIPFILTER=no MKISCSI=no MKLDAP=no MKKMOD=no MKKERBEROS=no MKLIBSTDCXX=no MKLVM=no MKMAN=no MKLINT=no MKPOSTFIX=no MKPROFILE=no MKSHARE=no ./build.sh -m milkymist -u -U $* build
