#	$NetBSD: Makefile,v 1.11 2011/07/17 20:54:48 joerg Exp $

INCSDIR= /usr/include/lm32

INCS=	ansi.h asm.h aout_machdep.h \
	bswap.h \
	cdefs.h cpu.h cpu_counter.h \
	cpuset.h \
	elf_machdep.h endian_machdep.h \
	frame.h float.h \
	intr.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	limits.h lock.h \
	mcontext.h mutex.h math.h \
	param.h pcb.h pmap.h \
	proc.h profile.h psl.h pte.h ptrace.h \
	reg.h registers.h rwlock.h \
	setjmp.h signal.h \
	trap.h types.h \
	vmparam.h \
	wchar_limits.h

.include <bsd.kinc.mk>
