#	$NetBSD: Makefile.inc,v 1.27 2012/07/09 18:12:11 ysionneau Exp $
#
#	etc.milkymist/Makefile.inc -- milkymist-specific etc Makefile targets
#

# If you change the list of distributed kernels, don't forget
# to update the release documentation in distrib/notes/common/contents

KERNEL_SETS=		GENERIC GENERIC_MFS

