/*
 * COPYRIGHT (C) 2013 Yann Sionneau <yann.sionneau@gmail.com>
 */

#include <lm32/asm.h>

// TODO: implement suword
ENTRY(suword)

// TODO: implement susword
ENTRY(susword)

// TODO: implement suswintr
ENTRY(suswintr)

// TODO: implement subyte
ENTRY(subyte)

// TODO: implement fuswintr
ENTRY(fuswintr)

// TODO: implement kcopy
ENTRY(kcopy)

// TODO: implement setjmp
ENTRY(setjmp)

// TODO: implement longjmp
ENTRY(longjmp)
