INCSDIR= /usr/include/milkymist

INCS=	ansi.h asm.h \
	autoconf.h bswap.h bus_defs.h bus_funcs.h \
	cdefs.h cpu.h cpu_counter.h csr.h \
	disklabel.h elf_machdep.h endian.h \
	endian_machdep.h frame.h \
	int_const.h int_fmtio.h int_limits.h int_mwgwtypes.h int_types.h \
	intr.h irqhandler.h limits.h lock.h \
	mutex.h mcontext.h param.h pcb.h pmap.h proc.h profile.h \
	psl.h pte.h ptrace.h reg.h rwlock.h \
	signal.h trap.h types.h uart.h userret.h \
	vmparam.h wchar_limits.h

.include <bsd.kinc.mk>
